### ISSUE TITLE
Error in tag name

### ISSUE THREAD

**Issue by TheRockman** [SimeonC/md-date-time#1]
The tag for this is "time-date-picker" not "text-date-picker".

**Comment by SimeonC** [comment]
Oops!! I'll fix it up once I'm done moving next week. Thanks for pointing this out.

Thanks,
~Simeon

Sent from my iPhone

On 14/01/2015, at 10:19 pm, TheRockman <notifications@github.com<mailto:notifications@github.com>> wrote:

The tag for this is not .

##
