### ISSUE TITLE
[FEAT] Date Range

### ISSUE THREAD

**Issue by amcdnl** [SimeonC/md-date-time#11]
Date ranges.  Select first date and then select last date and show a bar between them like ui-bootstrap's.

**Comment by scanferla** [comment]
+1

**Comment by SimeonC** [comment]
I don't understand what your asking for here - ui-bootstrap doesn't seem to have an example of this that I can find?

**Comment by rbarriuso** [comment]
+1

**Comment by reginaldlouis** [comment]
Looking forward for this feature.

**Comment by amcdnl** [comment]
@SimeonC sorry I was mistaken, I confused it with a different control but you get what i was talking about.

**Comment by mfaizanshaikh** [comment]
@SimeonC amcdnl is talking about the date range feature. If you can add it, it would be perfect.
Example date range picker:
https://github.com/dangrossman/bootstrap-daterangepicker

**Comment by sergonius** [comment]
It would be a lot cooler if you could just select 2 dates from the same calendar, duplicating the calendar doesn't look very good.

**Comment by SimeonC** [comment]
:+1: OK, I get what that's on about, yea we can probably do that in some cool way.

**Comment by SimeonC** [comment]
Feature now being tracked in new repo: https://github.com/SimeonC/sc-date-time/issues/2
