### ISSUE TITLE
[FEAT] Dropdown

### ISSUE THREAD

**Issue by amcdnl** [SimeonC/md-date-time#12]
Should have the ability to invoke it from a input box and show below a dropdown.

**Comment by SimeonC** [comment]
This is implementation, and it depends on which library you are using as this process is different for angular-ui, angular-strap and angular-material.

**Comment by amcdnl** [comment]
I think a demo of a implementation would be ideal.

**Comment by SimeonC** [comment]
OK, I should be able to add it to the demo page at some point (over on https://github.com/SimeonC/sc-date-time in case you missed the other messages I put up), though it'll only be a bootstrap demo at first as that's what I'm currently working in.
