### ISSUE TITLE
locale doesn't work for "NOW", "SAVE", "CANCEL" buttons

### ISSUE THREAD

**Issue by manuzhang** [SimeonC/md-date-time#13]
My application is intended for Chinese users and I've included `angular-locale_zh-cn.js`. It's working for  Month, Day and other words in the date time picker except for "NOW", "SAVE" and "CANCEL" buttons.

**Comment by SimeonC** [comment]
Now I look into it, it looks like there are a few places we need some extra options for full Internationalisation. (for angular-locale Reference see here: https://docs.angularjs.org/guide/i18n).

In future I'll include a angular value that can be decorated for translations for all those other text values.

**Comment by SimeonC** [comment]
Over in the new repo this is done, see https://github.com/SimeonC/sc-date-time (version 1.0.0)
