### ISSUE TITLE
Picker looks strange on angular 1.4.0 and angular-material 0.9.0

### ISSUE THREAD

**Issue by jozsi** [SimeonC/md-date-time#16]
Hello,

The date picker looks pretty strange using angular 1.4.0 and angular-material 0.9.0.
![screen shot 2015-05-02 at 03 10 34](https://cloud.githubusercontent.com/assets/840815/7439088/d6087eda-f078-11e4-8203-e78b5ba333ba.png)
I've created a [CodePen](http://codepen.io/anon/pen/RPPJJZ) to demonstrate it.

**Comment by ghost** [comment]
I've this problem too on AngularJS (1.4.0)+AngularMaterial using time-date-picker:

Week days are broken for me, (I only see the first three days of the month).

![cy_avcwebzyosc4mrcafdq54spxp0ouotopf6xzycky](https://cloud.githubusercontent.com/assets/725804/7539164/4cb83648-f5a5-11e4-8a10-890238ff22e0.png)

**Comment by gngeorgiev** [comment]
+1

**Comment by PhilippCh** [comment]
Same for me. Unfortunately not usable in this condition :(

**Comment by khalilof** [comment]
looks very strange :(  nobody is doing this date picker correctly  -_-

**Comment by jail1** [comment]
Yes, could you please take a look at it? I really need it. It looks awful. They did make some changes to the material css library. that is why it looks like this.

**Comment by YogurtShen** [comment]
Angular 1.3.15 & material 0.9.4 have the same problem~

**Comment by ravitejaobelisk** [comment]
+1, I too have the same issue. Using Angular 1.3.15 and Angular Material  0.9.4

**Comment by sinujohn** [comment]
+1

**Comment by ivahaev** [comment]
This is because now `md-button` has bigger min size then early. Need to correct css or may be add extra class `.md-icon-button`

**Comment by sinujohn** [comment]
@ivahaev what is the correct css that should be added? Without that this project will be rendered useless

**Comment by vlio20** [comment]
+1

**Comment by isaackehle** [comment]
FWIW:  A couple of quick styling hacks to make it more useful until there's a real fix: 

```
.time-date > .control > .slider > .date-control .day-cell {
    width: 1.7rem !important;
    height: 1.7rem !important;
    min-width: .7rem !important;
}

.time-date > .control > .slider > .date-control > .headers {
    margin-top: -0.0rem !important;
    margin-left: .1rem !important;
}
```

**Comment by gngeorgiev** [comment]
@pgkehle tnx, will try it out

**Comment by sinujohn** [comment]
@pgkehle the date highlighting is an oval now instead of circle and there is a scrollbar which is not needed. Also the fix doesn't apply to time picker part. Stll its useful till there is a real fix. :)

![capture](https://cloud.githubusercontent.com/assets/866225/7981100/5517d2be-0aca-11e5-9bfc-8d4dc69ac42f.PNG)

**Comment by Tooa** [comment]
Same problem. Any hope to get this fixed?

**Comment by ivanhtp** [comment]
@pgkehle solution works very well. To give the @sinujohn problem a solution as well is just add the style: 
.time-date > .control > .slider > .date-control .day-cell  span{
    top: -10px;
    position: relative;
}

in my case its perfect.

**Comment by vlio20** [comment]
@ivahaev I have forked @homen3 plunker and created this http://codepen.io/vlio20/pen/VLWmjv plunker with the your and @pgkehle fix suggestions. As you can see it still not working :(

**Comment by sdebaun** [comment]
+1
the time picker part is also broken

**Comment by cavarzan** [comment]
+1

**Comment by zeeshanjan82** [comment]
+1

**Comment by alexzaporozhets** [comment]
+1

**Comment by oscarr-reyes** [comment]
I had to use @pgkehle code and tweak it a bit in order to make it look nice, and also had to some of the source code for the style margin on the days, even though i am still a noob on this kind of programming, i was able to adapt the style fix on my application using $mdDialog.

![datePicker](http://i.imgur.com/l1HF4wj.png)

but i notice there is a button on the right (without icon, could be i am not loading the proper icon) that should load another format of picking, maybe the hrs, but its empty

**Comment by Tooa** [comment]
> but i notice there is a button on the right (without icon, could be i am not loading the proper icon) that should load another format of picking, maybe the hrs, but its empty

Yes. There is a back and forward arrow. You need to include font-awesome in order to make it work/visible.

**Comment by TWithers** [comment]
Better looking fix for now: http://codepen.io/anon/pen/vOWxRr

Problem was new .md-button has min-width and min-height.  Setting min-height to 0 fixes the oval issue, and then you need to adjust the top by 5 more pixels to fix the issue.

Honestly though, angular team is working on a date/time picker for angular-material, so I imagine I will be switching when it is available.  Every update angular-material does seems to be a breaking change for this.

**Comment by ioriiod0** [comment]
+1

**Comment by markserbol** [comment]
We can't just target the `.md-button` and set the `min-height` and `min-width` to 0, but here's the minimal change that fixes the issue for me, both on date and time picker and on vertical orientation. http://codepen.io/markserbol/pen/KpRLVr

**Comment by sinujohn** [comment]
@markserbol that works :+1:

**Comment by albertski** [comment]
@markserbol Thanks that worked for me!

**Comment by lchioukh** [comment]
+1

**Comment by ghost** [comment]
@markserbol thank you that works for me as well
