### ISSUE TITLE
[Feature]: allow passing of an auto-date

### ISSUE THREAD

**Issue by ericodes** [SimeonC/md-date-time#17]
Is it possible currently to pass a date to the widget, which the widget would automatically start at? Currently it starts at the current date.

**Comment by Roundaround** [comment]
If you set a value to the bound ng-model scope variable, the widget will start at that date.  It's a little clunky and assumes you're using ng-model to bind the value (I assume this would be the case for 99% of people, but I could be wrong), but it gets the job done.

**Comment by ericodes** [comment]
Hm...I had that earlier, but I was also working on a directive that was using another directive that was using this :) Will look into whether this is a digest cycle issue.

Thanks for the response!

**Comment by SimeonC** [comment]
Over in the new repo this is done, see https://github.com/SimeonC/sc-date-time (version 1.0.0)
