### ISSUE TITLE
[Feature]: Autosave on user interaction

### ISSUE THREAD

**Issue by Roundaround** [SimeonC/md-date-time#21]
In my implementation I tweaked the sources to omit the action buttons at the bottom, but I ran into an issue.  The widget only saves to the bound model when the user clicks the save button...so I played around with the sources a bit and came up with some changes to make it autosave any time the user interacts with the widget.

If enough people would like this, I can write up my changes in clean checkout of the sources and submit a pull request, otherwise I'll just leave it here as a suggestion/feature request.

**Comment by RhysJevons** [comment]
Could you put your example up on codepen for us to see?

**Comment by Roundaround** [comment]
Unfortunately, the styling is garbage at the moment (I don't use plunker all that much so perhaps I missed something when trying to include angular-material?), but you can see a functional demo here: http://plnkr.co/edit/UAmIr9gkFhjiz2SYpPu1?p=preview

**Comment by SimeonC** [comment]
Over in the new repo this is done, see https://github.com/SimeonC/sc-date-time (version 1.0.0)
