### ISSUE TITLE
can't display on IE8 because of rem (root em) units

### ISSUE THREAD

**Issue by GregRar** [SimeonC/md-date-time#23]
Hi,
We found that date time picker is not IE8 compatible as it claims in readme (I mean real IE8, not emulator).

It's because it uses rem (root em) units in CSS which are not supported in IE8 

http://caniuse.com/#feat=rem

**Comment by SimeonC** [comment]
Ah, Ummm, well technically Angular-Material doesn't support IE8 either, nor do most libraries these days so I'm just going to remove it from the supported versions in the README. Thanks for pointing that out.

I think that may have been a copy-paste issue...
