### ISSUE TITLE
Cannot install using bower

### ISSUE THREAD

**Issue by mateeyow** [SimeonC/md-date-time#4]
Here is the error:

```
bower ENOTFOUND     Request to https://bower.herokuapp.com/packages/md-date-time failed: getaddrinfo ENOTFOUND bower.herokuapp.com
```

**Comment by SimeonC** [comment]
Yea, I had that a bit too, it's a bower issue - they seemed to be having some issues last week as I had this on all sorts of packages at odd times. If you try again now it will should be working.
