### ISSUE TITLE
I'm trying to install in rails + angularjs

### ISSUE THREAD

**Issue by pantic4114** [SimeonC/md-date-time#7]
I'm trying to install md-date-time, but there are two things that I don't understand. My project does not use angular-material, use materialcss, I'm using in a rails project. There are two things that I don't understand:
1. Where put the shim of the md-button?.
2. Step 2 of usage. Where add the dependency to mdDateTime?
Sorry but i'm noob.
Thanks

**Comment by Newbsylberry** [comment]
There are a handful of different ways you can use angularJS with rails, but both the dependency and shim can be added where you define your angularJS app:

```
angular.module('yourApp', [
'mdDateTime'
])

.directive('mdButton', [function(){
    return {
        replace: true,
        restricte: 'E',
        transclude: true,
        template: '<button class="btn btn-link md-button" ng-transclude></button>'
    };
}]);

```

Alternatively you can add the directive to a separate file: 

```
angular.module('yourApp')
  .directive('mdButton', [function(){
    return {
        replace: true,
        restricte: 'E',
        transclude: true,
        template: '<button class="btn btn-link md-button" ng-transclude></button>'
    };
}]);
```

This will keep things organized as your project grows, just make sure to include it in your application.js or index.html file!
