### ISSUE TITLE
Year selection is spotty

### ISSUE THREAD

**Issue by TWithers** [SimeonC/md-date-time#8]
I notice that the year selection is overlapped by the select, so it is fairly hard to change the year on both FF and Chrome.

To resolve the issue, adding `width:100%;` on line 116-117 of the Styleus file seems to resolve the issue.

Adding a small margin (0.5rem) between the month and year helps break up the text a little as well.

As far as I can tell, I haven't seen any issues with those numbers, but I have only been playing around with it for 20 minutes.

**Comment by TWithers** [comment]
Also, just noticed `.date-control` should maybe have `overflow-y:hidden`.  Look at March 2014 for example.  Months with 6 rows in the calendar show the scroll bar.

**Comment by SimeonC** [comment]
Thanks for pointing that out - I'll get it fixed up ASAP.
