### ISSUE TITLE
[FEAT] Clock mode

### ISSUE THREAD

**Issue by amcdnl** [SimeonC/md-date-time#9]
On one of your comments here https://github.com/angular/material/issues/648 you show a clock picker. Personally I prefer that over the up down, is that still available?

**Comment by SimeonC** [comment]
No, I ended up removing it as I couldn't find a clean way of allowing editing of minutes on that version without using a number input below which kind of messed up the look/feel a bit.

There's an older version of it here that has the clockface: http://codepen.io/SimeonC/pen/XJdWPy

TBH I liked the clock too, but I didn't have time to try figure out the minutes UI which the spec omits completely - if you have any suggestions on how to do this (or you fancy doing it yourself) I'm all ears!

**Comment by amcdnl** [comment]
Ya, I'm planning to use it on my project.  Going to help out if your willing to PRs.  I think we should make it an option.  Have you seen the bootstrap clock one; how do they handle this?

**Comment by SimeonC** [comment]
I've no idea, didn't know bootstrap had a clock version.

**Comment by georgebarbarosie** [comment]
This one seems to be closest to the material design behavoiour http://weareoutman.github.io/clockpicker/ so I believe @amcdnl might have had it in mind.

**Comment by SimeonC** [comment]
I do like that way of doing hours/minutes, though it could do with a bit of work, the double layer on selecting hours is a little confusing.

If we take that option but show both the minute and hour hands, highlighting the hand you are selecting and showing either minutes or hours around the face I think that could work.

**Comment by amcdnl** [comment]
Have you seen this? http://material-ui.com/#/components/time-picker

**Comment by SimeonC** [comment]
That's not a bad implementation either. Common to all the implementations I've seen so far, that I want to figure some way around, is that "jump" you get when selecting an hour and it switches to minutes. That feels jarring to me.

**Comment by SimeonC** [comment]
Feature now being tracked in new repo: https://github.com/SimeonC/sc-date-time/issues/3
